steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-flask-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-flask-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - todo-flask-app
    - --image=gcr.io/$PROJECT_ID/todo-flask-app
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
